#!/bin/bash

POKEMON="pikachu"
URL="https://pokeapi.co/api/v2/pokemon/$POKEMON"
OUTPUT="data.json"
ERROR_LOG="errors.txt"

curl -s -f "$URL" -o "$OUTPUT"
if [ $? -ne 0 ]; then
    echo "$(date): Failed to fetch $POKEMON" >> "$ERROR_LOG"
else
    echo "Successfully fetched $POKEMON data."
fi

