#!/bin/bash
FILE="data.json"

# Extract data using jq
NAME=$(jq -r '.name' "$FILE" | sed 's/\b\(.\)/\u\1/')   
TYPE=$(jq -r '.types[0].type.name' "$FILE" | sed 's/\b\(.\)/\u\1/')
WEIGHT=$(jq -r '.weight' "$FILE")
HEIGHT=$(jq -r '.height' "$FILE")


FORMATTED_WEIGHT=$(echo "$WEIGHT" | awk '{print $1/10}')  
FORMATTED_HEIGHT=$(echo "$HEIGHT" | awk '{print $1/10}')  


echo "$NAME is of type $TYPE, weighs ${FORMATTED_WEIGHT}kg, and is ${FORMATTED_HEIGHT}m tall."
